### ISSUE TITLE
Problems using adding tabulated bonded interactions

### ISSUE THREAD

**Issue by GDeichmann** [uchicago-voth/MSCG-release#1]
Hi,

I am currently trying to perform MS-CG on a generic LJ polymer system.
I would like to provide Boltzmann-inverted interactions for my bonded interactions.
After various attempts I was not able to reproduce the LJ potential I used to generate the input trajectories (using all atoms as CG sites) and I was getting suspicious that something in the code might not be working as expected.

To my surprise even when running the table_fm example I was not able to recover the provided results with my version of the code, futher indicating something may be buggy. Running the example with the "none" option for the bonded potential generates identical results to using the "tab" option.

I suspect that, due to some bug, the forces from the bond are not substracted at all from the total force.
Is this a known bug? and has anyone attempted to solve it?
In order to further track down what is actually happening (or not happening) could someone point me to the location in the code where the force substraction is supposed to take place?

Thanks a lot in advance
Gregor Deichmann

**Comment by tdlafage** [comment]
Hello Gregor, 

Thanks for bringing this to my attention. I am working now to solve the issue. 

The force from tabulated is subtracted in the accumulate_tabulated_forces function at line 952 in matrix.cpp. 

Best,
Thomas

**Comment by tdlafage** [comment]
Hello Gregor,

I just made a commit that should fix the problem you were describing. I tested this on the table_fm example and I get agreement between the code's output and the files in the output directory.

Happy force-matching,
Thomas
