### ISSUE TITLE
Question about: Cannot create a BSpline with fewer control points (2) than the spline order (3).

### ISSUE THREAD

**Issue by DzWangCH** [uchicago-voth/MSCG-release#11]
Hi, dear all,
I was using /rangefinder.x and /newfm.x run MSCG for my CG system. And then here shows this Error:

Cannot create a BSpline with fewer control points (2) than the spline order (3).
Either decrease the bin width or decrease the spline order for this interaction.

I tried to change "pair_nonbonded_bspline_basis_order" and "pair_nonbonded_basis_set_resolution " and "pair_nonbonded_output_binwidth "
When I change resolution too small then there will show another problem like:
Current number of frames in this trajectory is too low to provide a fully-determined set of FM equations. Provide more frames in the input trajectory.
I would ask, how could a define spline order properly?
In addition, from example folder I found an another method to run MSCG, which through 
fix 1 all mscg 1 range on
fix 1 all mscg 1
these two commands do that. What`s the main different between these two method? Why the data in both rmin.in and rmin_b.in from these two method are different? (I used unwrapp coordinate)
Thanks for your help

**Comment by pakles** [comment]
The first warning/error has to do with the number of knots (or control points) that are generated for each interaction. Most likely, it is a symptom of either wrong units or misdefined topology. If you're using standard Gromacs TRR/XTC, you'll want your units to be in nm. If you're using standard LAMMPS trajectories (using real units), you'll want your units to be in Angstrom. 

Are you force-matching only nonbonded interactions or also bonded interactions? In the latter case, you will want to adjust your pair_bond_basis_set_resolution. Let's say you're using a bond basis resolution of 0.5 and rangefinder only finds a bond that samples 2.5 < rij < 3.2. The generated b-spline won't have enough control points given a b-spline order of 3. 

The second method is using the LAMMPS fix via the MSCG library. It should be functionally equivalent to the MSCG binaries.

**Comment by DzWangCH** [comment]
Thanks for your reply, for convenient here is my control.in file:
block_size 1
start_frame 1
n_frames 30
nonbonded_cutoff 16.7
basis_type 0
excluded_style 0
primary_output_style 0
output_solution_flag 1
output_spline_coeffs_flag 1
pair_nonbonded_bspline_basis_order 3
angle_bspline_basis_order 3
dihedral_bspline_basis_order 3
pair_bond_bspline_basis_order 3
pair_nonbonded_basis_set_resolution 0.03
pair_bond_basis_set_resolution 0.03
angle_basis_set_resolution 0.03
dihedral_basis_set_resolution 0.03
pair_nonbonded_output_binwidth 0.7
pair_bond_output_binwidth 0.7
angle_output_binwidth 0.7
dihedral_output_binwidth 0.7
matrix_type 0
------------------------------------------------------
------------------------------------------------------
When I tried to increase resolution the first error will show up, and is 30 frames too few to run newfm.x? As you said I also tried to use LAMMPS fix command with same input files, but some dihedral is disabled (the value in rmin_b.in is none). My system used unwarpped coordinates, is that the reason for these different?

**Comment by pakles** [comment]
No. unwrapped coordinates is fine. Note that there are some problems with dihedrals and it's currently not recommended. 

Can you provide your top and rmin files and 1 frame of your trajectory? 

Also, 30 frames is likely too small to have significant statistics.

**Comment by DzWangCH** [comment]
Thanks again for your reply. Here are my files, cg_petg.dump is one frame you asked.

-------------------------------------------------------
Mit freundlichen Grüßen
Dongze Wang

University Stuttgart

70569 Stuttgart

Tel: +49 15259696502

E-Mail: dongz_wang@h<mailto:wolfgang.verestek@imwf.uni-stuttgart.de>otmail.com

<http://aka.ms/weboutlook>
________________________________
发件人: pakles <notifications@github.com>
发送时间: 2020年5月12日 15:22
收件人: uchicago-voth/MSCG-release <MSCG-release@noreply.github.com>
抄送: DzWangCH <dongz_wang@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [uchicago-voth/MSCG-release] Question about: Cannot create a BSpline with fewer control points (2) than the spline order (3). (#11)


No. unwrapped coordinates is fine. Note that there are some problems with dihedrals and it's currently not recommended.

Can you provide your top and rmin files and 1 frame of your trajectory?

Also, 30 frames is likely too small to have significant statistics.

**Comment by pakles** [comment]
Hmm, I don't see any attachments. Please provide the top.in, rmin.in, rmin_b.in, and cg_petg.dump

**Comment by DzWangCH** [comment]
Sorry about that, here again is attachment

[cg.zip](https://github.com/uchicago-voth/MSCG-release/files/4616972/cg.zip)

**Comment by pakles** [comment]
Ah, I see the problem. Your 5-5 interaction only samples between 16.64 and 16.7 Angstroms. With a B-spline resolution of 0.03, the code tries to construct a B-spline lacking too many control points. Your 1-1 interaction is similar but has just enough range to not throw the problem. You can either (1) remove 5-5 from force-matching, (2) redefine your mapping, or (3) gather more statistics if you think the current range is unreasonably small.

**Comment by DzWangCH** [comment]
In top.in file it needs only one molecule information (if all molecules are same type) or should contains all informations for each molecule? And sometime "It appears that the file is no longer open. Please check that you are not attempting to read past the end of the file and try again."
I met this error, what it means?

**Comment by pakles** [comment]
Yes, the top.in file only needs to template each molecule type once. So if your simulation contains the same molecule types, you only need one set of topology information. 

That error means it reached the end of your trajectory file. You probably requested too many frames to read.
