### ISSUE TITLE
Units of forces in dihedral potentials

### ISSUE THREAD

**Issue by vklip** [uchicago-voth/MSCG-release#2]
Hello,

I am currently trying to get familiar with the MS-CG code. While I was trying to reproduce some atomistic potentials, in this particular case using an dihedral potential.  The resulting force-matched force-field was off my expectations by a scaling factor  of exactly 2*pi/360. (Whereas the potential energies were correct)

To me it looks like the forces are calculated in units of energy-units per radiant. For simulations with the GROMACS package the forces need to be tabulated  per degree. As far as I know, the same holds for LAMMPS. Furthermore I noticed angular forces seem to be calculated per degree. 

My question is if this is on purpose.  If not, it may be nice to be consistent with common simulations packages. 

 

Thanks in advance,
Viktor Klippenstein

**Comment by tdlafage** [comment]
Hello Viktor,

The issue has been resolved. Both the force and the potential are scaled by same factor. 

Best,
Thomas
