### ISSUE TITLE
C++ standard compliance of MSCG / variable length arrays

### ISSUE THREAD

**Issue by akohlmey** [uchicago-voth/MSCG-release#3]
We're currently doing a C++ standard compliance audit of the LAMMPS MD code, which interfaces with MSCG. One common issue is the use for "variable length arrays", which is accepted by most C++ compilers, but conflicts with the C++ standard.
https://gcc.gnu.org/onlinedocs/gcc/Variable-Length.html

We've addressed most of the issues in LAMMPS here: https://github.com/lammps/lammps/pull/889
but it looks like MSCG has some variable length arrays in its headers, that are imported into LAMMPS.

It would be nice, if this could be addressed, since the LAMMPS developers would like to include a test for C++ standard compliance into our continuous integration testing, and that collides - among a few other packages - with MSCG.

Thanks in advance for your consideration.

**Comment by tdlafage** [comment]
Hello Axel,

We took a look at this and I will see about getting these arrays compliant to the standard tomorrow or the day after. 

Best,
Thomas

**Comment by tdlafage** [comment]
Hello Axel,

I have made a new commit that removes the compilation warning messages when building LAMMPS with MSCG with the -pedantic flag. It looks like you already made all the necessary changes in fix_mscg.h and fix_mscg.cpp. Please let me know if there is something else you would like me to do. 

Best,
Thomas

**Comment by akohlmey** [comment]
@tdlafage thanks. Please understand that this is not only a LAMMPS issue, but a general issue of complying with C++ standards. We just noticed it recently in LAMMPS when checking for C++11 compliance. Several changes of this kind had crept into the code base over the years.
From looking at the changes in your commit, it looks like you are now introducing a memory leak since you add `new` operators without the corresponding `delete[]`. (this is why variable length arrays are so convenient: they are allocated on the stack and thus are automatically freed, when they go out of scope). The risk of using them in C++ code is, that support for it may go away at any time, and that there is no guarantee, that they work with any C++ compiler (most do, because they default to be compatible to C).

**Comment by tdlafage** [comment]
Hello Axel,

Yeah, the commit name was not the best. I think the description reflects your sentiment that it is a C++ standards issue, not a LAMMPS issue. I pushed a new commit that adds `delete[]` operators corresponding to the `new` operators. 

Best,
Thomas
