### ISSUE TITLE
Release tags are missing on github

### ISSUE THREAD

**Issue by junghans** [uchicago-voth/MSCG-release#5]
Please push the release tags for `v1.6.9`, `v1.7.0` and future releases to github.

Otherwise, it is really hard to remember that git hash version 1.7.0 actually was.

**Comment by junghans** [comment]
`v1.7.0` is missing?

**Comment by tdlafage** [comment]
I set that one to commit `aabf1f2`.

**Comment by junghans** [comment]
I don't see it here: https://github.com/uchicago-voth/MSCG-release/tags

**Comment by tdlafage** [comment]
it is there: https://github.com/uchicago-voth/MSCG-release/releases/tag/1.7.0

**Comment by junghans** [comment]
One last wish, could you tag a release that includes #4.

**Comment by tdlafage** [comment]
Done. It is called 1.7.3.1

**Comment by junghans** [comment]
Thanks!
