### ISSUE TITLE
Problem when installing package MSCG

### ISSUE THREAD

**Issue by tienp** [uchicago-voth/MSCG-release#6]
Hi,

I have followed the steps to build and install the MSCG package but when it comes to the last step,  make machine, it returns:
-----------------------
$ make yes-MSCG
Installing package MSCG
$ make mpi
make[1]: Entering directory '/home/tien/Apps/lammps-16Mar18/src/Obj_mpi'
make[1]: Leaving directory '/home/tien/Apps/lammps-16Mar18/src/Obj_mpi'
make[1]: Entering directory '/home/tien/Apps/lammps-16Mar18/src/Obj_mpi'
mpicxx -g -O3 -std=c++11  -DLAMMPS_GZIP -DLAMMPS_MEMALIGN=64 -I../../lib/mscg/includelink  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1   -std=c++11  -c ../fix_mscg.cpp
../fix_mscg.cpp: In constructor ‘LAMMPS_NS::FixMSCG::FixMSCG(LAMMPS_NS::LAMMPS*, int, char**)’:
../fix_mscg.cpp:48:12: error: invalid use of incomplete type ‘class LAMMPS_NS::Comm’
   me = comm->me;
            ^
In file included from ../pointers.h:26:0,
                 from ../fix.h:17,
                 from ../fix_mscg.h:23,
                 from ../fix_mscg.cpp:21:
../lammps.h:32:9: note: forward declaration of ‘class LAMMPS_NS::Comm’
   class Comm *comm;              // inter-processor communication
         ^
../fix_mscg.cpp:49:16: error: invalid use of incomplete type ‘class LAMMPS_NS::Comm’
   nprocs = comm->nprocs;
                ^
In file included from ../pointers.h:26:0,
                 from ../fix.h:17,
                 from ../fix_mscg.h:23,
                 from ../fix_mscg.cpp:21:
../lammps.h:32:9: note: forward declaration of ‘class LAMMPS_NS::Comm’
   class Comm *comm;              // inter-processor communication
         ^
Makefile:104: recipe for target 'fix_mscg.o' failed
make[1]: *** [fix_mscg.o] Error 1
make[1]: Leaving directory '/home/tien/Apps/lammps-16Mar18/src/Obj_mpi'
Makefile:160: recipe for target 'mpi' failed
make: *** [mpi] Error 2

----------------
I tried on CentOS and Ubuntu 16.04, both returned the same error. Is it a known bug? Or I missed something on the way?

Thanks a lot in advance,

Tien Phan

**Comment by pakles** [comment]
Hi Tien,

Thanks for pointing this out. I'll try to track down the problem. In the meantime, could you please revert to the Aug 2017 version of LAMMPS and retry to compile? 

Thanks,
Alex

**Comment by pakles** [comment]
Ignore the above. It looks like fix_mscg.cpp in the Mar2018 version (on stable) of LAMMPS is missing an include to comm.h. This seems to have been fixed in the May2018 version of LAMMPS (on master). If you include this line (e.g., after #include "fix_mscg.h"):

`#include "comm.h"`

you should be good to go. Let us know if this works.

Alex

**Comment by tienp** [comment]
Hi Alex,

Thanks for your reply. I included the "comm.h" as you suggested, but it also got stuck at:

 ../../lib/mscg/liblink/libmscg.a(matrix.o): In function `accumulate_accumulation_matrices(MATRIX_DATA*)':
matrix.cpp:(.text+0x8ca): undefined reference to `dgeqrf_'
matrix.cpp:(.text+0x932): undefined reference to `dgeqrf_'
matrix.cpp:(.text+0x986): undefined reference to `dgeqrf_'
../../lib/mscg/liblink/libmscg.a(matrix.o): In function `solve_accumulation_form_fm_equations(MATRIX_DATA*)':
matrix.cpp:(.text+0x1210): undefined reference to `dgelss_'
matrix.cpp:(.text+0x1291): undefined reference to `dgelss_'
../../lib/mscg/liblink/libmscg.a(matrix.o): In function `solve_accumulation_form_bootstrapping_equations(MATRIX_DATA*)':
matrix.cpp:(.text+0x3f97): undefined reference to `dgelss_'
matrix.cpp:(.text+0x4022): undefined reference to `dgelss_'
../../lib/mscg/liblink/libmscg.a(matrix.o): In function `solve_this_BI_equation(MATRIX_DATA*, int&)':
matrix.cpp:(.text+0x6ed6): undefined reference to `dgelsd_'
matrix.cpp:(.text+0x6f52): undefined reference to `dgelsd_'
../../lib/mscg/liblink/libmscg.a(matrix.o): In function `solve_sparse_fm_normal_equations(MATRIX_DATA*)':
matrix.cpp:(.text+0x96c5): undefined reference to `dgetrf_'
matrix.cpp:(.text+0x96ee): undefined reference to `dgetri_'
../../lib/mscg/liblink/libmscg.a(matrix.o): In function `solve_dense_fm_normal_equations(MATRIX_DATA*)':
matrix.cpp:(.text+0xa820): undefined reference to `dgelsd_'
matrix.cpp:(.text+0xa8ae): undefined reference to `dgelsd_'
matrix.cpp:(.text+0xb9c1): undefined reference to `dgelsd_'
matrix.cpp:(.text+0xba3a): undefined reference to `dgelsd_'
matrix.cpp:(.text+0xc17f): undefined reference to `dgetrf_'
matrix.cpp:(.text+0xc1a2): undefined reference to `dgetri_'
../../lib/mscg/liblink/libmscg.a(matrix.o): In function `solve_dense_fm_normal_bootstrapping_equations(MATRIX_DATA*)':
matrix.cpp:(.text+0xcbc8): undefined reference to `dgelsd_'
matrix.cpp:(.text+0xcc54): undefined reference to `dgelsd_'
collect2: error: ld returned 1 exit status
Makefile:89: recipe for target '../lmp_mpi' failed
make[1]: *** [../lmp_mpi] Error 1
make[1]: Leaving directory '/home/tien/Apps/lammps-16Mar18/src/Obj_mpi'
Makefile:160: recipe for target 'mpi' failed
make: *** [mpi] Error 2

It seems that the "matrix.cpp" in the MSCG couldnot use the link library but I have no ideas to fix that. Could you have a look at it?

Thanks,

Tien

**Comment by pakles** [comment]
Could you make sure you are linking to lapack libraries when you compile the external mscg library and in the lammps Makefile (e.g., in /lib/mscg/Makefile.lammps in the lammps directory)?

**Comment by tienp** [comment]
Yeah, adding -llapack in the lammps Makefile as you suggested solves the problem!  

Thank you so much.

Best, 

Tien
